version: "3.8"

networks:
  gitea:
    external: false

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 15s
      timeout: 5s
      retries: 3

  app:
    image: gitea/gitea:latest
    environment:
      # - USER_UID=1000
      # - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - app-volume:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db


volumes:
  app-volume:
  db-volume:
